version: "3"
services:
  mongo:
    container_name: mongo-container
    image: mongo:3
    restar: always
    volumes:
      - ./data:/data/db
    ports:
      - "25017:25017"
  api:
    container_name: api-container
    build: .
    image: clean-node-api
    restar: always
    volumes:
      - ./dist:/usr/src/clean-node-api/dist
    command: yarn start
    ports:
      - "5050:5050"
    links:
      - mongo
